apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api-gb
  namespace: two-containers
  labels:
    name: deploy-api-gb
    type: api

spec:
  template:
    metadata:
      name: api-gb
      labels:
        app: api-gb
        type: api
    spec:
      containers:
        - name: php-gb
          image: fndiaz/php-custom:v1
          ports:
            - containerPort: 9000
        - name: nginx-gb
          image: fndiaz/nginx-custom:localhost
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: api-gb