apiVersion: v1
kind: Service
metadata:
  name: mongo-gb
  namespace: two-containers
  labels:
    name: mongo-gb

spec:
  ports:
    - targetPort: 27017
      port: 27017
  selector:
    app: mongo-gb