apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api-gb
  namespace: custom-image
  labels:
    name: deploy-api-gb
    type: api

spec:
  template:
    metadata:
      name: api-gb
      labels:
        app: api-gb
        type: api
    spec:
      containers:
        - name: api-gb
          #image: fndiaz/app-init:v0.02
          image: 069138660701.dkr.ecr.us-east-2.amazonaws.com/custom-image:redis
          ports:
            - containerPort: 80
  replicas: 20
  selector:
    matchLabels:
      app: api-gb