apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api-gb
  labels:
    name: deploy-api-gb
    type: api

spec:
  template:
    metadata:
      name: api-gb
      labels:
        app: api-gb
        type: api
    spec:
      containers:
        - name: api-gb
          image:
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: api-gb