apiVersion: v1
kind: Service
metadata:
  name: service-api-gb
  labels:
    name: service-api-gb

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002
  selector:
    app: api-gb