---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: asg-php-gb
  namespace: sb2c-homol
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: deploy-php-gb
  minReplicas: 40
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50

