apiVersion: v1
kind: ConfigMap
metadata:
  name: env-homol-local
  namespace: sb2c-homol
data:
  .env: |
    APP_NAME="Ghost Busters"
    APP_ENV=local
    APP_KEY=hkNQJ7HJ0J%aGcallXdj40jb2IqqRr%U
    APP_DEBUG=true
    APP_URL=http://lab-alb-1356247616.us-east-2.elb.amazonaws.com/api/v1
    APP_TIMEZONE=UTC
    #LOG_CHANNEL=kinesis
    LOG_CHANNEL=stack
    LOG_KINESIS_VERSION=latest
    LOG_KINESIS_KEY=
    LOG_KINESIS_SECRET=
    LOG_KINESIS_DELIVERY_STREAM_NAME=log-test
    DB_CONNECTION=mongodb
    DB_HOST=mongo-gb
    DB_PORT=27017
    DB_DATABASE=ghostbusters
    #REDIS_HOST=redis-gb
    REDIS_HOST=redis-gb.sb2c.internal
    CACHE_DRIVER=redis
    QUEUE_CONNECTION=sync
    SENTRY_DSN=https://3cff45e737244a3dbc43bbc941e4cc7a@sentry.io/1400378
    #EXCEPTION_RENDER=json
    DOCTRINE_CACHE_DISABLED=true