apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-gb
  labels:
    name: deploy-nginx-gb
    type: nginx

spec:
  template:
    metadata:
      name: nginx-gb
      labels:
        app: nginx-gb
        type: nginx
    spec:
      containers:
        - name: nginx-gb
          image: fndiaz/nginx-custom
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: nginx-gb