apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-php-gb
  labels:
    name: deploy-php-gb
    type: php

spec:
  template:
    metadata:
      name: php-gb
      labels:
        app: php-gb
        type: php
    spec:
      containers:
        - name: php-gb
          image: fndiaz/php-custom:opcache
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: php-gb